local events = {}

-- From COMBATLOG_EVENT_LIST global
events.CombatLogEvents = {
	"ENVIRONMENTAL_DAMAGE",
	"SWING_DAMAGE",
	"SWING_MISSED",
	"RANGE_DAMAGE",
	"RANGE_MISSED",
	"SPELL_CAST_START",
	"SPELL_CAST_SUCCESS",
	"SPELL_CAST_FAILED",
	"SPELL_MISSED",
	"SPELL_DAMAGE",
	"SPELL_HEAL",
	"SPELL_ENERGIZE",
	"SPELL_DRAIN",
	"SPELL_LEECH",
	"SPELL_SUMMON",
	"SPELL_RESURRECT",
	"SPELL_CREATE",
	"SPELL_INSTAKILL",
	"SPELL_INTERRUPT",
	"SPELL_EXTRA_ATTACKS",
	"SPELL_DURABILITY_DAMAGE",
	"SPELL_DURABILITY_DAMAGE_ALL",
	"SPELL_AURA_APPLIED",
	"SPELL_AURA_APPLIED_DOSE",
	"SPELL_AURA_REMOVED",
	"SPELL_AURA_REMOVED_DOSE",
	"SPELL_AURA_BROKEN",
	"SPELL_AURA_BROKEN_SPELL",
	"SPELL_AURA_REFRESH",
	"SPELL_DISPEL",
	"SPELL_STOLEN",
	"ENCHANT_APPLIED",
	"ENCHANT_REMOVED",
	"SPELL_PERIODIC_MISSED",
	"SPELL_PERIODIC_DAMAGE",
	"SPELL_PERIODIC_HEAL",
	"SPELL_PERIODIC_ENERGIZE",
	"SPELL_PERIODIC_DRAIN",
	"SPELL_PERIODIC_LEECH",
	"SPELL_DISPEL_FAILED",
	"DAMAGE_SHIELD",
	"DAMAGE_SHIELD_MISSED",
	"DAMAGE_SPLIT",
	"PARTY_KILL",
	"UNIT_DIED",
	"UNIT_DESTROYED",
	"SPELL_BUILDING_DAMAGE",
	"SPELL_BUILDING_HEAL",
	"UNIT_DISSIPATES",
	"SPELL_EMPOWER_START",
	"SPELL_EMPOWER_END",
	"SPELL_EMPOWER_INTERRUPT",
}

-- From DBM-Core.lua:noArgTableEvents
events.NoArgsTableEvents = {
	SWING_DAMAGE = true,
	SWING_MISSED = true,
	RANGE_DAMAGE = true,
	RANGE_MISSED = true,
	SPELL_DAMAGE = true,
	SPELL_BUILDING_DAMAGE = true,
	SPELL_MISSED = true,
	SPELL_ABSORBED = true,
	SPELL_HEAL = true,
	SPELL_ENERGIZE = true,
	SPELL_PERIODIC_ENERGIZE = true,
	SPELL_PERIODIC_MISSED = true,
	SPELL_PERIODIC_DAMAGE = true,
	SPELL_PERIODIC_DRAIN = true,
	SPELL_PERIODIC_LEECH = true,
	SPELL_DRAIN = true,
	SPELL_LEECH = true,
	SPELL_CAST_FAILED = true,
}

events.ArgTableEvents = {}

for _, v in ipairs(events.CombatLogEvents) do
	if not events.NoArgsTableEvents[v] then
		events.ArgTableEvents[v] = true
	end
end

return events